### ISSUE TITLE
Possible defect

### ISSUE THREAD

**Issue by luukau** [btaens/cakephp-hier-auth#2]
Hi,

Using your plugin, I got some strange results when building the authorised roles list if the user is a 'system administrator'. I think there might be a defect on line# 104 in the validate function:

```
103:        if (isset($this->_acl[$controller][$this->_allSign])) {
104:            $authRoles = array_merge($this->_acl[$controller][$this->_allSign]);
105:        }
```

should possibly be:

```
103:        if (isset($this->_acl[$controller][$this->_allSign])) {
104:            $authRoles = array_merge($this->_acl[$controller][$this->_allSign], $authRoles);
105:        }
```

If not corrected the $authRoles array may get overwritten at this stage and not appended, which I don't think is the expected behaviour. Happy to be corrected :)

PS: Like your plugin btw and looking at extending at some point.

Cheerio,
Luuk

**Comment by btaens** [comment]
Ah, nice catch. Strange it never came up in my project.

**Comment by btaens** [comment]
Okay, fixed.
